### ISSUE TITLE
Inquiring about revenue #'s on dev tees

### ISSUE THREAD

**Issue by Jdoyle112** [jglovier/ama#10]
Hey man, I stumbled on dev tees and think it's pretty similar to something I'm interested in building but for designers. I understand this is a lot to ask but I'm wondering if you'd be willing to share what kind of revenue #'s you're getting with dev tees? I'd really appreciate it, just trying to get an idea of what to expect.

Thanks :)

PS. love your portfolio site! Might be my favorite one ever by a designer/ developer.

**Comment by jglovier** [comment]
Hi @Jdoyle112! The one thing I've learned from creating Dev Tees is that running a t-shirt business is hard...and not very lucrative. 😄 

When I started the project, I was able to raise about $2k on Kickstarter for the inaugural shirt, [the Hacker tee](https://www.kickstarter.com/projects/jag/hacker-t-shirt). It was enough to fund production of the shirts for backers and order extra inventory to sell on my website.

About a year later when I decided to launch [9 more shirts on Kickstarter](https://www.kickstarter.com/projects/jag/dev-tees) under the Dev Tees brand, I blew past my $6k funding goal and raised over $32k, about half of which was used on production of the shirts, several thousand more on other fulfillment related costs (like shipping, and the other rewards like buttons and stickers), and I was left with a few thousand in profits.

Eventually I learned that holding inventory and selling it via website takes a lot of effort that I didn't have due to my full-time job and other life and family responsibilities. 

Also, I learned that inventory has a shelf life. Eventually you have to start selling it at a discount to even move it, and some of it will just never sell because you can't 100% accurately predict how much demand there will be for each permutation of size/color/design when you are ordering the initial run.

So last year I moved to [Amazon Merch](http://merch.amazon.com/) and switched to a print-on-demand business model that has allowed me to just create new designs as I'm able, upload the, and not even think about it after that.

The downside is you still have to drive traffic to your products on Amazon in order for them to sell, and that does take time. 

I really haven't the time and capacity to do that, so my sales have suffered considerable. I still get a few customers each week who buy some shirts just from organic traffic to devtees.com, but rarely adds up to more than $20-$30 a month if I'm not actively using my mailing list to communicate with my customer base (which I have not been 🙈).

When I *do* send out Dev Tees emails, I'll see a spike in sales for a few days, sometimes resulting in $100-$200 in profit for the month.

So like I said, it's not a terribly lucrative business model I have going. 😊 I mostly just do it because I like making t-shirts for people to wear.

PS - if you're interested in designing and selling shirts but not interested in taking on all the hassle of the t-shirt business thing, you may want to check out [Cotton Bureau](https://cottonbureau.com/), [Society6](https://society6.com/), [Zazzle](https://www.zazzle.com/), [Spreadshirt](https://www.spreadshirt.com/), or one of the many other services that let you basically just provide the design and sell it on their marketplace.

Good luck, and thanks for the kind words about my site design!! :blush: :v:

**Comment by jglovier** [comment]
Also, for context, my email list is about 1200 subscribers right now. That's what I really should be doing more of us communicating with that list...but alas the whole time thing.

If you can build a list of people who are interested in what you are making, you'll get the majority of your revenue from offering them compelling and interesting products. And also by not emailing them too much because people don't want to receive email too often. 

When I am able to actively engage my list, I've found that sending a monthly or quarterly email is about the sweet spot for my audience at least.
