### ISSUE TITLE
What are good UX design principles?

### ISSUE THREAD

**Issue by sukrosono** [jglovier/ama#4]
Hi how are you?

Would you mind explain to me what the conceptual good UX design is?
It's hard to search the conceptual and also fundamental about UX design for web which also should able to applied to the mobile (in general case) . I found it easier to search material about technical rather than the conceptual :sob: 

lately i just feel stupid and exhausted when my time and energy focused on technical syntax on writing code but the result still doesn't match user desire nor expectation.

**Comment by jglovier** [comment]
@brutalcrozt Hi! 👋  Great question. Let me take a few days to come up with a thoughtful answer and get back to you. 👍

**Comment by jglovier** [comment]
> Would you mind explain to me what the conceptual good UX design is?

This is a great question, honestly. And I'm not sure I can do it justice here, but I'll try. 😄 

So first of all let me say that there are definitely good resources available on the philosophy behind creating great user experiences. A few that spring to mind:
- [Don't Make Me Think](https://www.amazon.com/dp/0321965515/ref=pd_lpo_sbs_dp_ss_1?pf_rd_p=1944687442&pf_rd_s=lpo-top-stripe-1&pf_rd_t=201&pf_rd_i=0321344758&pf_rd_m=ATVPDKIKX0DER&pf_rd_r=SJZR8K1ZKYK5JCZDD1Q3) (book by Steven Krug)
- [The Design of Everyday Things](https://www.amazon.com/Design-Everyday-Things-Revised-Expanded/dp/0465050654/ref=sr_1_1?s=books&ie=UTF8&qid=1467809655&sr=1-1&keywords=design+of+everyday+things) (book by Don Norman)
- [Lean UX](https://www.amazon.com/Lean-UX-Applying-Principles-Experience/dp/1449311652/ref=sr_1_1?s=books&ie=UTF8&qid=1467809679&sr=1-1&keywords=lean+ux) (book by Jeff Gothelf)

Here are a few of the things I've learned over the years from studying this topic, designing and building software for people, and from working with very smart colleagues:
- Guide people toward accomplishing their objectives. _(see also [Jobs To Be Done](https://strategyn.com/customer-centered-innovation-map/) framework)_
- Don't lead people to dead ends.
- Don't leave people wondering what to do (i.e. making them think).
- A good experience works well across whatever device or screen size the user is on.
- Leverage familiar trends and conventions rather than introducing confusing new paradigms.
- A good experience is fast (performant) because users don't wait.
- Keep workflows shallow and simple. _(i.e. don't create long and complex workflows)_
- Knowing the balance between less and more is more important than just choosing one.
- Unique parts of a product should look distinct from other parts.

There's lots of other important things to remember (both conceptual and technical), but these are some of the top things that come to mind for me first.

Also here's a couple overview-type articles on Smashing Magazine that are relevant:
- [What Is User Experience Design? Overview, Tools And Resources](https://www.smashingmagazine.com/2010/10/what-is-user-experience-design-overview-tools-and-resources/)
- [The Lean UX Manifesto: Principle-Driven Design](https://www.smashingmagazine.com/2014/01/lean-ux-manifesto-principle-driven-design/)
