### ISSUE TITLE
How would you call the GitHub's design style?

### ISSUE THREAD

**Issue by andreygrehov** [jglovier/ama#8]
GitHub design is neither skeuomorphic nor flat. I would call it "almost flat", but is there a better term? It seems the design is inspired by desktop applications, but I can be wrong. Would love to learn more about this style.

**Comment by jglovier** [comment]
Hi @andreygrehov! Great question, and to be honest, I'm not sure what I would call it either!! 😆 We haven't really used any descriptive names for the style we have. As you have observed, it does have some elements of skeuomorphism, and some elements of flat design.

In general we tend to lean toward guiding principles in design implementation that don't necessarily favor a defined style. We tend to use shadows when giving depth is important for page and visual hierarchy, and lines to help support the distinction of regions.

But largely these days we're trying to be especially mindful of designing and building components that fit into our design system [Primer](https://primer.github.io/).

When I'm working on features for the site I'm always trying to consider how I can reduce visual complexity to amplify content or action signals. This often means trying to remove as much as possible until I'm left with the minimum visual change/addition to the page, which is important because our app has so many different facets, features, and workflows that there's not really room for anything that's not absolutely necessary.

Of course, this is more of an ideal goal/standard to aim for, and in reality we do often end up shipping things that we later need to go back and iterate on, reducing complexity and refining as appropriate. But striking a balance between polishing to perfection and shipping a solution that can be iterated on is a healthy tension to embrace.

IDK if that answers your question, but I hope it gives you a little insight into our process. LMK if you have any other questions. :heart: :v:
